version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=costing_app.py  # Set the Flask app to costing_app
      - FLASK_ENV=production
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_DEFAULT_REGION=your_region
      - AWS_BACKUP_BUCKET=your_bucket_name
    volumes:
      - .:/app
      - ./team_planner.db:/app/team_planner.db

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    depends_on:
      - web